import * as E from './engine.js';
import {BALANCE, FLEET_TYPES, CARGO, LEVELS} from './balance.js';
import {World} from './world.js';
import {OUTLINE} from './data.js';
import {money, signedMoney as signed} from './format.js';
import {renderHUD} from './hud-render.js';
import {stationArt, fleetIllustration} from './railway-art.js';

const $ = (s,root=document)=>root.querySelector(s);
const fullMoneyText = value => String(value ?? '').replace(/(\d[\d \u00a0\u202f]*(?:[.,]\d+)?)\s*млн\s*₸/g,(_,n)=>money(Number(n.replace(/[ \u00a0\u202f]/g,'').replace(',','.'))));
const esc = value => fullMoneyText(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = (v,d=0) => Number(v||0).toLocaleString('ru-RU',{maximumFractionDigits:d});
const names = {stationRepair:'Ремонт станции',lineRepair:'Ремонт участка',upgrade:'Модернизация станции',tracks:'Дополнительный путь',electrify:'Электрификация',newLine:'Новая линия'};
const cargoNames = {coal:'Уголь',oil:'Нефть',goods:'Товары'};
const fleetNames = {diesel:'Тепловоз',electric:'Электровоз',coal:'Угольные полувагоны',oil:'Нефтяные цистерны',goods:'Крытые вагоны'};
const glyphs = {
 advisor:'M5 21v-3a7 7 0 0 1 14 0v3 M8 8a4 4 0 1 0 8 0 M7 8h10 M9 4h6 M19 3h3v5h-3l-2 2V3Z',
 station:'M3 21V9l9-6 9 6v12 M2 21h20 M9 21v-6h6v6 M6 11h2m8 0h2 M11 7h2',
 rails:'M8 2 4 22M16 2l4 20 M7 4h10M6 8h12M5 13h14M4 19h16',
 train:'M6 3h12v13H6z M8 7h8 M8 11h2m4 0h2 M8 16l-3 5m11-5 3 5 M7 19h10',
 map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Z M9 3v16m6-14v16',
 build:'m14 4 6 6 M12 6l6 6 M3 21l11-11 M13 3l8 8 M4 18l2 2',
 contract:'M6 3h9l4 4v14H6z M14 3v5h5 M9 12h7 M9 16h5',
 fleet:'M3 6h11v11H3z M14 10h5l2 4v3h-7 M6 20h.01M17 20h.01 M6 17v3m11-3v3',
 chart:'M4 3v17h17 M8 15V9m5 6V5m5 10v-4',
 engineer:'M5 21v-3a7 7 0 0 1 14 0v3 M8 7a4 4 0 0 0 8 0 M6 7h12 M9 6V3h6v3',
 clock:'M12 8v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',
 arrow:'M4 12h16m-6-6 6 6-6 6',
 close:'m6 6 12 12M6 18 18 6',
 plus:'M12 5v14M5 12h14',minus:'M5 12h14',
 target:'M9 12h6m-3-3v6 M5 3H3v4m14-4h4v4M3 17v4h4m10 0h4v-4',
 layers:'m3 8 9-5 9 5-9 5Z M3 12l9 5 9-5 M3 16l9 5 9-5',
 alert:'m12 3 10 18H2Z M12 9v5m0 3v.1',
 check:'m5 12 4 4L19 6',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M10 2h4l1 3 3 1 3 2-2 3v2l2 3-3 2-3 1-1 3h-4l-1-3-3-1-3-2 2-3v-2l-2-3 3-2 3-1Z',
 volume:'M11 4 5 9H2v6h3l6 5z M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',
 mute:'M11 4 5 9H2v6h3l6 5z m5 5 6 6m0-6-6 6',
 save:'M4 3h13l4 4v14H3V3z M7 3v6h9V3 M7 21v-8h10v8',
 leaf:'M20 3C7 2 2 8 5 15s16 2 15-12Z M4 21 16 8',
 snow:'M12 2v20M3 7l18 10M3 17 21 7 M8 4l4 4 4-4M8 20l4-4 4 4',
 sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
 coal:'m3 15 4-9 7-3 6 7 1 8-12 3Z M7 6l3 8-1 7m1-7 10-4',
 oil:'M12 2S5 11 5 15a7 7 0 0 0 14 0c0-4-7-13-7-13Z M9 15c0 2 1 3 3 3',
 goods:'m3 6 9-4 9 4v13l-9 3-9-3Z M3 6l9 4 9-4M12 10v12 M7 4l9 4v5',
 lock:'M6 10h12v11H6z M8 10V6a4 4 0 0 1 8 0v4 M12 14v3',
 bolt:'m13 2-8 12h7l-1 8 8-13h-7z',
 repair:'M14 3a6 6 0 0 0-7 8l-5 6 4 4 6-6a6 6 0 0 0 8-7l-4 4-4-4Z',
 medal:'m8 3 4 6 4-6 M7 3H3l6 9m8-9h4l-6 9 M18 15a6 6 0 1 1-12 0 6 6 0 0 1 12 0',
 history:'M3 11a9 9 0 1 1 2 7 M3 4v7h7 M12 7v6l4 2',
 help:'M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 3v.1 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',
 flag:'M5 22V3m0 1c5-5 9 5 15 0v10c-6 5-10-5-15 0',
 chevron:'m9 5 7 7-7 7',
 heart:'M12 21 3 12C-2 5 6 0 12 7c6-7 14-2 9 5Z',
 wallet:'M3 5h16v16H3z M3 5V3h13v2 M14 10h7v6h-7Z M17 13h.01'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${glyphs[name]||glyphs.train}"/></svg>`;
const why = text => `<details class="why"><summary>Почему?</summary><p>${text}</p></details>`;
const seasonNames=['Зима','Весна','Лето','Осень'];
const seasonIcons=['snow','leaf','sun','leaf'];
const quarterName=q=>`${['I','II','III','IV'][q%4]} квартал · ${2026+Math.floor(q/4)}`;
let load = E.loadGame();
let state = load.ok && load.state ? load.state : E.createGame();
let selected = null;
let currentForecast, currentModal=null, layer='network', animating=false, animationTimer, mailTimer, mailOpening=false, sound=false, audioContext, toastTimer;
try{sound=localStorage.getItem('ktz-sound')==='1';}catch{}
const world = new World($('#world'),{onSelect:s=>{if(animating)return;closeModal();selected=s;render();}});
const station = id => state.stations.find(s=>s.id===id);
const line = id => state.lines.find(l=>l.id===id);
const stationName=id=>station(id)?.name||id||'—';
const routeName=(a,b)=>`${esc(stationName(a))} → ${esc(stationName(b))}`;
const isOver = ()=>['bankrupt','dismissed','arrested'].includes(state.status);
function beep(type='click'){if(!sound)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();const osc=audioContext.createOscillator(), gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);osc.type='sine';osc.frequency.setValueAtTime(type==='turn'?660:type==='error'?180:460,audioContext.currentTime);gain.gain.setValueAtTime(.035,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.13);osc.start();osc.stop(audioContext.currentTime+.13);}catch{}}
function toast(text){$('#toast').textContent=fullMoneyText(text);$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function save(){const result=E.saveGame(state);if(!result.ok)toast(result.message);return result;}
function apply(result,after){beep(result.ok?'click':'error');toast(result.message|| (result.ok?'Готово':'Действие недоступно'));if(result.ok){save();render();if(after)after(result);}return result;}
function actionCard(type,target,label,description,svg){const q=E.projectQuote(state,{type,target});return `<button class="action-card ${!q.ok?'locked':''}" data-action="project" data-type="${type}" data-target="${target}">${icon(svg)}<div><b>${label}</b><small>${esc(description||q.message)}</small></div><span class="price">${q.requiredLevel>E.engineerLevel(state)?`Ур. ${q.requiredLevel}`:money(q.cost)}</span></button>`;}
function projectName(p){const l=line(p.target);return station(p.target)?.name||(l?stationName(l.a)+' → '+stationName(l.b):stationName(p.a)+' → '+stationName(p.b));}
function render(){
 currentForecast=E.forecast(state);const f=currentForecast,c=E.getCorridor(state),level=E.engineerLevel(state);
 $('#app').innerHTML=renderHUD({state,f,c,level,selected,animating,sound,layer,icon,esc,num,money,signed,quarterName,seasonNames,seasonIcons,names,detailHTML,projectName});
 $('#app').inert=animating||Boolean($('#modal-root .modal-backdrop'));
 world.update(state,currentForecast,selected);world.setLayer(layer);
}
function miniWindow(title,subtitle,body,extra=''){
 currentModal=title;hideTip();$('#app').inert=false;
 $('#modal-root').innerHTML='<section class="mini-window '+extra+'" role="dialog" aria-label="'+esc(title)+'"><div class="mini-window-header"><div><div class="eyebrow">'+subtitle+'</div><h2>'+title+'</h2></div><button class="icon-btn" data-action="close-modal" aria-label="Закрыть">'+icon('close')+'</button></div><div class="mini-window-content">'+body+'</div></section>';
 $('.mini-window button')?.focus({preventScroll:true});
}
function engineerCard(){
 const level=E.engineerLevel(state),current=LEVELS[level-1],next=LEVELS[level];
 const progress=next?Math.min(100,(state.xp-current.xp)/(next.xp-current.xp)*100):100;
 miniWindow('Ваш инженер','Личное дело',
 '<div class="mini-profile"><img src="./assets/engineer-avatar.png" alt="Инженер"><div><strong>'+esc(current.name)+'</strong><small>Казахстанские магистрали</small></div></div><p>Начинал с небольшого участка. Теперь под вашим руководством соединяет города, развивает станции и открывает стране новые пути.</p><div class="mini-stat-grid"><div><label>Уровень</label><b>'+level+' / 5</b></div><div><label>Репутация</label><b>'+num(state.reputation)+' / 100</b></div><div><label>Опыт</label><b>'+num(state.xp)+'</b></div><div><label>Стаж управления</label><b>'+Math.max(0,state.quarter-BALANCE.startingQuarter)+' кв.</b></div></div><div class="progress"><i style="width:'+progress+'%"></i></div><p style="margin-top:9px">'+(next?'До «'+esc(next.name)+'» — '+num(Math.max(0,next.xp-state.xp))+' опыта.':'Вы достигли высшего инженерного уровня.')+'</p><h3>Доступные возможности</h3><p>'+esc(current.unlock)+'</p><button class="primary teal" data-action="engineer">'+icon('medal')+' Навыки и достижения</button>','engineer-window');
}
function networkCard(){const f=currentForecast;
 miniWindow('Обзор сети','Пульс магистралей','<p>Прогноз перевозок и результата на текущий квартал.</p><div class="stats-row"><span>Доставим</span><b>'+num(f.delivered,1)+' тыс. т</b></div><div class="stats-row"><span>Не выполнено</span><b class="'+(f.unserved>0?'negative':'positive')+'">'+num(f.unserved,1)+' тыс. т</b></div><div class="stats-row"><span>Станции / направления</span><b>'+state.stations.length+' / '+state.lines.length+'</b></div><div class="stats-row"><span>В работе</span><b>'+state.projects.length+' проектов</b></div><div class="stats-row"><span>Результат</span><b class="'+(f.net>=0?'positive':'negative')+'">'+signed(f.net)+'</b></div><button class="text-btn" data-action="finance">Подробный расчёт '+icon('arrow')+'</button>');
}
function advisorCard(){const f=currentForecast;
 const advice=state.insolvencyQuarters>0?'Бюджет ниже нуля. Сократите дефицит перевозок или привлеките кредит до конца восстановительного периода.':f.unserved>1?'Спрос выше возможностей сети. Проверьте самый загруженный участок, затем станции и подходящий грузу парк.':state.projects.length?'Работы идут. Подготовьте локомотивы и вагоны к росту перевозок после завершения проектов.':'Развивайте навыки и соединяйте этапы коридора Китай → Европа. Договоры обеспечат развитие доходом.';
 miniWindow('Советник','Рядом на каждом этапе','<div class="work-detail-icon">'+icon('advisor')+'</div><p>'+advice+'</p>'+(f.warnings||[]).slice(0,2).map(w=>'<div class="warning">'+esc(typeof w==='string'?w:w.message||w.text||'Проверьте ограничения сети.')+'</div>').join('')+'<h3>Следующий шаг</h3><p>'+(E.engineerLevel(state)===1?'Завершайте ремонт и доставляйте грузы. На втором уровне откроются дополнительные пути.':'Следите за мощностью всего маршрута: улучшение одного узла помогает, когда остальные готовы к росту.')+'</p><button class="primary teal" data-action="bottleneck">'+(f.unserved>1?'Найти узкое место':'План развития')+' '+icon('arrow')+'</button>');
}
function workCard(id){const p=state.projects.find(p=>p.id===id);if(!p)return;const progress=Math.max(0,Math.min(100,(p.duration-p.remaining)/p.duration*100)),ic=['upgrade','stationRepair'].includes(p.type)?'station':p.type==='electrify'?'bolt':'rails';
 const target=station(p.target)?{type:'station',id:p.target}:line(p.target)?{type:'line',id:p.target}:{type:'station',id:p.a};
 miniWindow(names[p.type],esc(projectName(p)),'<div class="work-detail-icon">'+icon(ic)+'</div><div class="stats-row"><span>Готовность</span><b>'+num(progress)+'%</b></div><div class="progress"><i style="width:'+progress+'%"></i></div><div class="stats-row"><span>Осталось</span><b>'+p.remaining+' кв.</b></div><div class="stats-row"><span>Вложения</span><b>'+money(p.cost)+'</b></div><p style="margin-top:14px">Работы продвигаются при завершении хода. После готовности новые мощности сразу войдут в прогноз сети.</p><button class="primary teal" data-action="select-'+target.type+'" data-id="'+esc(target.id)+'">Показать на карте '+icon('arrow')+'</button>');
}
function openMail(){
 const r=state.reports[0];if(!r||mailOpening||animating)return;closeModal();mailOpening=true;hideTip();$('#app').inert=true;
 $('.quarter-mail')?.classList.add('envelope-opening');const button=$('[data-action="open-mail"]');if(button)button.disabled=true;
 mailTimer=setTimeout(()=>{mailOpening=false;state.uiLastReadReportQuarter=r.quarter;save();render();reportModal(r);},matchMedia('(prefers-reduced-motion: reduce)').matches?100:700);
}
function hideTip(){const tip=$('#hover-tip');if(tip){tip.classList.remove('visible');tip.setAttribute('aria-hidden','true');}}
function showTip(el){if(!el||animating)return;const tip=$('#hover-tip');tip.innerHTML='<b>'+esc(el.getAttribute('aria-label')||'')+'</b><span>'+esc(el.dataset.tip)+'</span>';tip.classList.add('visible');tip.setAttribute('aria-hidden','false');const r=el.getBoundingClientRect(),t=tip.getBoundingClientRect();let x=r.left+r.width/2-t.width/2,y=r.top-t.height-15;if(r.left<110&&r.top>105){x=r.right+16;y=r.top+(r.height-t.height)/2;}if(y<10)y=r.bottom+15;tip.style.left=Math.max(10,Math.min(innerWidth-t.width-10,x))+'px';tip.style.top=Math.max(10,Math.min(innerHeight-t.height-10,y))+'px';}
document.addEventListener('pointerover',e=>{const el=e.target.closest('[data-tip]');if(el&&!el.contains(e.relatedTarget))showTip(el);});
document.addEventListener('pointerout',e=>{const el=e.target.closest('[data-tip]');if(el&&!el.contains(e.relatedTarget))hideTip();});
document.addEventListener('focusin',e=>showTip(e.target.closest('[data-tip]')));
document.addEventListener('focusout',hideTip);
document.addEventListener('click',hideTip);
function detailHTML(){
 if(selected.type==='line'){
  const l=line(selected.id);if(!l){selected={type:'station',id:'karaganda'};return detailHTML();}
  const load=currentForecast.edgeLoads?.[l.id]||{};
  return `<div class="detail-head"><div class="eyebrow">${icon('train')} Железнодорожный участок</div><div class="detail-title"><h2 style="font-size:19px">${esc(stationName(l.a))}<br>→ ${esc(stationName(l.b))}</h2><span class="pill ${(load.ratio||0)>.88?'danger':''}">${(load.ratio||0)>.88?'Узкое место':'В работе'}</span></div><p class="detail-sub">${num(l.distance)} км · ${l.tracks} ${l.tracks===1?'путь':'пути'} · ${l.electrified?'электротяга':'теплотяга'}</p></div><div style="height:75px;display:flex;align-items:center;justify-content:center;color:#376d68;gap:16px">${icon('train')}<span style="letter-spacing:5px;color:#9caf9b">━━━━━━━━━━</span>${icon(l.electrified?'bolt':'train')}</div><div class="detail-body"><div class="detail-metrics"><div class="metric"><label>Состояние</label><strong>${num(l.condition)}<small> / 100</small></strong>${conditionBar(l.condition)}</div><div class="metric"><label>Загрузка</label><strong>${num((load.ratio||0)*100)}<small>%</small></strong></div><div class="metric"><label>Мощность</label><strong>${num(load.capacity,1)}<small> тыс. т</small></strong></div><div class="metric"><label>Перевезено</label><strong>${num(load.load,1)}<small> тыс. т</small></strong></div></div><div class="section-label">Развитие участка</div>${actionCard('lineRepair',l.id,'Отремонтировать','Восстановить пропускную способность','repair')}${actionCard('tracks',l.id,'Добавить путь','Увеличить пропускную способность','build')}${!l.electrified?actionCard('electrify',l.id,'Электрифицировать','Открыть маршрут электровозам','bolt'):''}${why('Мощность зависит от числа путей, состояния, сезона и временных работ. Маршрут также ограничивают станции и общий парк. '+(l.via?`Схематическое направление через ${esc(l.via)}.`:''))}${l.playerBuilt?'<p class="detail-note">Новая игровая линия, построенная вами.</p>':''}</div>`;
 }
 const s=station(selected.id)||station('karaganda');const load=currentForecast.stationLoads?.[s.id]||{};
 return `<div class="detail-head"><div class="eyebrow">${icon('train')} Станция</div><div class="detail-title"><h2>${esc(s.name)}</h2><span class="pill">${s.level} уровень</span></div><p class="detail-sub">${({coal:'Угольный центр',capital:'Столица · главный узел',port:'Каспийский порт',oil:'Нефтяной регион',gateway:'Международные ворота',junction:'Пересадочный узел',industry:'Промышленный узел',grain:'Зерновой регион'})[s.kind]||'Региональный узел'}</p></div>${stationArt(s.level)}<div class="detail-body"><div class="detail-metrics"><div class="metric"><label>Состояние</label><strong>${num(s.condition)}<small> / 100</small></strong>${conditionBar(s.condition)}</div><div class="metric"><label>Мощность / квартал</label><strong>${num(E.stationCapacity(state,s.id),1)}<small> тыс. т</small></strong></div><div class="metric"><label>Выполнено · прогноз</label><strong>${num(load.load,1)}<small> тыс. т</small></strong></div><div class="metric money-metric"><label>Вклад в выручку</label><strong>${money(load.revenue)}</strong></div></div><div class="section-label">Развитие станции</div>${s.level<3?actionCard('upgrade',s.id,`Повысить до уровня ${s.level+1}`,'Новые платформы и мощности','build'):''}${actionCard('stationRepair',s.id,'Отремонтировать','Восстановить состояние','repair')}${state.reports[0]?`<p class="detail-note">Прошлый квартал: ${num(state.reports[0].stationLoads?.[s.id]?.load,1)} тыс. т · ${money(state.reports[0].stationLoads?.[s.id]?.revenue)} выручки через узел.</p>`:''}${why('Ремонт восстанавливает состояние, модернизация повышает базовую мощность. Перевозки распределяются по всей сети. Вклад станции — доля выручки проходящих договоров, а не дополнительный доход.')}</div>`;
}
function conditionBar(condition){return `<div class="condition-bar">${Array.from({length:10},(_,i)=>`<i class="${i*10>=condition?'off':''}"></i>`).join('')}</div>`;}
function modal(title,subtitle,body,footer='',small=false){
 const previous=currentModal;currentModal=title;hideTip();$('#app').inert=true;
 $('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${small?'small':''} ${title==='Квартал завершён'?'report-window':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-header"><div><div class="eyebrow">${subtitle}</div><h2>${title}</h2></div><button class="icon-btn" data-action="close-modal" aria-label="Закрыть">${icon('close')}</button></div><div class="modal-content">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}</section></div>`;
 if(previous!==title)setTimeout(()=>$('.modal button, .modal input, .modal select')?.focus({preventScroll:true}),20);
}
function closeModal(){clearTimeout(mailTimer);mailOpening=false;$('.quarter-mail')?.classList.remove('envelope-opening');const mail=$('[data-action="open-mail"]');if(mail)mail.disabled=false;currentModal=null;$('#app').inert=animating;$('#modal-root').innerHTML='';}
function projectModal(proposal){
 if(proposal.type==='electrify'&&proposal.target==='shu-kyzylorda'&&!line(proposal.target)){modal('Сначала нужна новая линия','Зависимость этапа',`<p>Электрификация станет доступна после завершения линии Шу → Кызылорда. Сначала постройте её, затем вернитесь к этому этапу.</p>`,`<button class="primary teal" data-action="stage" data-id="central-shortcut">Открыть проект линии</button>`,true);return;}

 const q=E.projectQuote(state,proposal), label=proposal.target?(station(proposal.target)?.name||line(proposal.target)&&routeName(line(proposal.target).a,line(proposal.target).b)||proposal.target):routeName(proposal.a,proposal.b);
 modal(names[proposal.type],esc(label),`${proposal.type==='upgrade'&&station(proposal.target)?`<div class="station-evolution">${stationArt(station(proposal.target).level)}<span aria-hidden="true">→</span>${stationArt(Math.min(3,station(proposal.target).level+1))}</div>`:''}<div class="compare"><div><label>Сейчас</label><strong>${esc(typeof q.before==='object'?JSON.stringify(q.before):q.before??'—')}</strong></div><span class="arrow">→</span><div><label>После проекта</label><strong class="positive">${esc(typeof q.after==='object'?JSON.stringify(q.after):q.after??'—')}</strong></div></div><div class="grid-two"><div class="card"><div class="eyebrow">Инвестиции</div><div class="big-number" style="font-size:25px;margin-top:8px">${money(q.cost)}</div></div><div class="card"><div class="eyebrow">Срок работ</div><div class="big-number" style="font-size:25px;margin-top:8px">${q.duration||'—'} кварт.</div></div></div><p>${q.cost!==undefined?`Изменение перевозок: ${q.impact>=0?'+':''}${num(q.impact,1)} тыс. т / кв. Изменение результата: ${signed(q.netImpact)} / кв.`:esc(q.message)}</p>${(q.warnings||[]).map(w=>`<div class="warning">${icon('alert')} ${esc(w)}</div>`).join('')}${!q.ok?`<div class="warning">${esc(q.message)}${q.requiredLevel>E.engineerLevel(state)?` Требуется уровень инженера ${q.requiredLevel}; сейчас — ${E.engineerLevel(state)}.`:''}</div>`:''}${q.cost>state.budget-Math.max(0,currentForecast.expenses)?`<div class="warning">После вложения останется ${money(state.budget-q.cost)}. Ближайшие расходы сети: ${money(currentForecast.expenses)}. Сопоставьте их с прогнозом выручки ${money(currentForecast.revenue)}.</div>`:''}${why('Оплата списывается при запуске. Объект меняется только после завершения работ; в это время его доступная мощность может снизиться. Оценка учитывает действующие договоры, другие проекты могут изменить итог.')}`,`<button class="secondary" data-action="close-modal">Позже</button><button id="confirm-project" title="${q.affordable===false?'Недостаточно средств':esc(q.message)}" class="primary teal" ${!q.ok||q.affordable===false||isOver()?'disabled':''}>Начать строительство ${icon('arrow')}</button>`,true);
 $('#confirm-project')?.addEventListener('click',()=>apply(E.startProject(state,proposal),()=>{closeModal();}));
}
function buildModal(tab='projects'){
 const c=E.getCorridor(state);
 modal('Строим сеть будущего','Инфраструктура',`<div class="tab-strip"><button data-action="build" data-tab="projects" class="${tab==='projects'?'active':''}">Текущие работы</button><button data-action="build" data-tab="network" class="${tab==='network'?'active':''}">Станции и участки</button><button data-action="build" data-tab="new" class="${tab==='new'?'active':''}">Новая линия</button></div>${tab==='projects'?`${state.projects.length?state.projects.map(p=>`<div class="card" style="margin-bottom:10px"><div class="card-top"><h3>${names[p.type]}</h3><span class="pill warn">Осталось ${p.remaining} кв.</span></div><p>${esc(p.target?(station(p.target)?.name||line(p.target)&&routeName(line(p.target).a,line(p.target).b)):routeName(p.a,p.b))}</p><div class="progress"><i style="width:${Math.max(5,(1-p.remaining/p.duration)*100)}%"></i></div><p>Вложено ${money(p.cost)} · объект изменится после окончания работ</p></div>`).join(''):'<div class="info">Пока нет активных строек. Выберите станцию или участок на карте либо откройте список сети.</div>'}<h3>Ближайшие этапы коридора</h3>${c.stages.filter(s=>!s.done).slice(0,3).map(s=>`<button class="list-link" data-action="stage" data-id="${s.id}"><span>${esc(s.label)}<small class="subtle" style="display:block;margin-top:5px">Уровень инженера ${s.requiredLevel}</small></span>${icon('chevron')}</button>`).join('')}`:tab==='network'?`<div class="station-levels">${[1,2,3].map(stationArt).join('')}</div><div class="grid-two"><div><h3>Станции</h3>${state.stations.map(s=>`<button class="list-link" data-action="select-station" data-id="${s.id}"><span>${esc(s.name)}<small class="subtle" style="display:block">Уровень ${s.level} · состояние ${num(s.condition)}%</small></span>${icon('chevron')}</button>`).join('')}</div><div><h3>Участки</h3>${state.lines.map(l=>`<button class="list-link" data-action="select-line" data-id="${l.id}"><span style="font-size:12px">${routeName(l.a,l.b)}<small class="subtle" style="display:block">${l.tracks} пут. · ${num(l.condition)}%</small></span>${icon('chevron')}</button>`).join('')}</div></div>`:newLineHTML()}`);
 if(tab==='new')wireNewLine();
}
function newLineHTML(){const opts=state.stations.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');return `<p>Выберите узлы и промежуточные точки. Игровая трасса учитывает длину и сложность местности; она не изображает реальный строительный проект.</p><div class="grid-two"><div class="form-row"><label for="line-a">Начальная станция</label><select id="line-a">${opts}</select></div><div class="form-row"><label for="line-b">Конечная станция</label><select id="line-b">${opts}</select></div></div><div class="form-row"><label>Корректировка трассы</label><div id="waypoints"></div><button class="secondary" id="add-waypoint">${icon('plus')} Промежуточная точка</button><span class="subtle">Широта и долгота в пределах Казахстана. Можно добавить до трёх точек.</span></div><canvas id="route-design" width="740" height="230" style="width:100%;height:230px;border-radius:12px;background:#e9dcc0" aria-label="Предлагаемая трасса новой линии"></canvas><div id="line-preview"></div><button class="primary teal full-width" id="quote-line">Рассчитать проект ${icon('arrow')}</button>`;}
function drawRouteDesign(canvas,proposal){
 const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;
 const project=p=>({x:25+(p.lon-46)*16.5,y:18+(56-p.lat)*12});
 ctx.clearRect(0,0,w,h);ctx.beginPath();OUTLINE.forEach(([lon,lat],i)=>{const p=project({lon,lat});i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.closePath();ctx.fillStyle='#c9b878';ctx.fill();ctx.strokeStyle='#d0a950';ctx.stroke();
 ctx.strokeStyle='#5d7c82';ctx.lineWidth=1;for(const l of state.lines){const a=project(station(l.a)),b=project(station(l.b));ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
 const points=[station(proposal.a),...(proposal.via||[]),station(proposal.b)].filter(Boolean).map(project);
 ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='#db8140';ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.stroke();ctx.setLineDash([]);
 for(const st of state.stations){const p=project(st);ctx.beginPath();ctx.arc(p.x,p.y,2.5,0,Math.PI*2);ctx.fillStyle='#123e54';ctx.fill();}
 points.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fillStyle='#de8a44';ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=2;ctx.stroke();ctx.font='bold 12px Segoe UI';ctx.fillStyle='#294c42';ctx.fillText(i===0?stationName(proposal.a):i===points.length-1?stationName(proposal.b):`Точка ${i}`,p.x+8,p.y-8);});
}
function wireNewLine(){
 $('#line-a').value='shu';$('#line-b').value='kyzylorda';let count=0;
 $('#add-waypoint').onclick=()=>{if(count>=3)return;count++;const div=document.createElement('div');div.className='grid-two';div.style.marginBottom='8px';div.innerHTML=`<input aria-label="Широта промежуточной точки ${count}" class="way-lat" type="number" step="0.1" min="41" max="56" value="44.4"><input aria-label="Долгота промежуточной точки ${count}" class="way-lon" type="number" step="0.1" min="46" max="88" value="69.5">`;$('#waypoints').append(div);$('#add-waypoint').disabled=count>=3;update();};
 const proposal=()=>({type:'newLine',a:$('#line-a').value,b:$('#line-b').value,via:[...$('#waypoints').children].map(e=>({lat:Number($('.way-lat',e).value),lon:Number($('.way-lon',e).value)}))});
 const update=()=>{const p=proposal();const q=E.projectQuote(state,p);drawRouteDesign($('#route-design'),p);$('#line-preview').innerHTML=`<div class="${q.ok?'info':'warning'}">${q.ok?`${money(q.cost)} · ${q.duration} кв. · перевозки ${q.impact>=0?'+':''}${num(q.impact,1)} тыс. т / кв.`:esc(q.message)}</div>`;};
 $('.modal-content').addEventListener('input',update);$('#quote-line').onclick=()=>projectModal(proposal());update();
}
function fleetModal(){
 const types=Object.keys(fleetNames);
 modal('Подвижной состав','Общий парк страны',`<div class="info">Локомотивы и грузовые вагоны работают в общем парке. Электровозы обслуживают только полностью электрифицированные маршруты. Покупка сразу меняет прогноз перевозок.</div><div class="grid-two">${types.map(type=>{const def=FLEET_TYPES[type]||{};return `<div class="card fleet-card">${fleetIllustration(type)}<div class="card-top"><div class="cargo-icon">${icon(type==='electric'?'bolt':['coal','oil','goods'].includes(type)?type:'train')}</div><span class="pill">${num(def.capacity)} тыс. т</span></div><h3 style="margin-top:15px">${fleetNames[type]}</h3><p>Содержание: ${money(def.maintenance)} / кв.<br>Срок службы: ${num(def.life)} кварталов</p><button class="secondary full-width" data-action="buy" data-type="${type}" ${isOver()?'disabled':''}>${icon('plus')} Купить · ${money(def.cost)}</button></div>`;}).join('')}</div><h3 style="margin-top:25px">В эксплуатации · ${state.fleet.length} ед.</h3>${state.fleet.map(v=>`<div class="fleet-row"><div class="cargo-icon">${icon(['coal','oil','goods'].includes(v.type)?v.type:v.type==='electric'?'bolt':'train')}</div><div><h4>${esc(v.name||fleetNames[v.type])}</h4><p>Состояние ${num(v.condition)}% · возраст ${v.age} / ${v.life} кв. · мощность ${num(v.capacity*(.4+.6*v.condition/100)*(v.age>=v.life?BALANCE.expiredFleetCapacity:1),1)} тыс. т</p></div><button class="secondary" data-action="repair-fleet" data-id="${v.id}" ${v.condition>=99||isOver()?'disabled':''}>${icon('repair')} Ремонт</button></div>`).join('')}${why('Для одного груза нужны и локомотив, и подходящие вагоны. Их эффективная мощность снижается по мере износа. Один и тот же парк нельзя одновременно засчитать нескольким договорам.')}`);
}
function contractsModal(tab='offers'){
 const offers=E.getOffers(state), f=currentForecast;
 modal('Грузы находят свой путь','Перевозки и договоры',`<div class="tab-strip"><button data-action="contracts" data-tab="offers" class="${tab==='offers'?'active':''}">Предложения · ${offers.length}</button><button data-action="contracts" data-tab="active" class="${tab==='active'?'active':''}">Действующие · ${state.contracts.filter(c=>c.end>state.quarter).length}</button></div>${tab==='offers'?offers.map(o=>`<article class="offer-card"><div class="cargo-icon">${icon(o.cargo)}</div><div class="offer-main"><div class="card-top"><h3>${esc(o.name)}</h3>${o.illegal?'<span class="pill danger">Подозрительный груз</span>':'<span class="pill">Новый офер</span>'}</div><p class="subtle" style="margin:3px 0">${routeName(o.from,o.to)}</p><div class="offer-stats"><span>${cargoNames[o.cargo]}</span><b>${num(o.volume,1)} тыс. т / кв.</b><span>${o.duration} кварт.</span><span>${money(o.price)} / тыс. т</span></div>${o.illegal?'<div class="warning">Документы на груз вызывают сомнения. Высокая оплата сопровождается риском проверки, штрафа, увольнения и уголовного преследования. Отказ безопасен.</div>':''}</div><div class="offer-actions"><button class="secondary" data-action="negotiate" data-id="${o.id}">Обсудить ${icon('arrow')}</button><button class="text-btn" data-action="reject-offer" data-id="${o.id}" style="align-self:center">Отказаться</button></div></article>`).join('')||'<div class="empty">Все предложения рассмотрены. Новые появятся в следующем квартале.</div>':state.contracts.filter(c=>c.end>state.quarter).map(c=>{const a=f.allocations.find(a=>a.contractId===c.id)||{};return `<article class="offer-card"><div class="cargo-icon">${icon(c.cargo)}</div><div class="offer-main"><div class="card-top"><h3>${esc(c.name)}</h3><span class="pill ${a.delivered<c.volume?'warn':''}">${c.start>state.quarter?'Будущий старт':c.illegal?'Риск проверки':'В работе'}</span></div><p class="subtle">${routeName(c.from,c.to)} · ${cargoNames[c.cargo]}</p><div class="offer-stats"><span>Спрос: ${num(a.demand??c.volume,1)} тыс. т</span><b>Выполнение: ${num(a.delivered,1)} тыс. т</b><span>${c.base?'Постоянный договор':`До ${quarterName(c.end-1)}`}</span></div>${why(esc(a.reason||'Перевозки начнутся в согласованный квартал.'))}${!c.base&&c.start<=state.quarter?`<button class="text-btn" data-action="cancel-contract" data-id="${c.id}" style="margin-top:12px">Расторгнуть договор</button>`:''}</div></article>`;}).join('')||'<div class="empty">Нет действующих договоров.</div>'}`);
}
function negotiationModal(id){
 const o=E.getOffers(state).find(x=>x.id===id);if(!o){toast('Предложение больше недоступно');contractsModal();return;}
 let price=o.price,volume=o.volume;
 modal('За столом переговоров',`${esc(o.name)} · ${cargoNames[o.cargo]}`,`<div class="info">${routeName(o.from,o.to)} · ${o.duration} кварталов. Стоимость указана за тысячу тонн фактически доставленного груза.</div>${o.illegal?'<div class="warning"><b>Советник рекомендует отказаться.</b> Есть признаки недостоверных сведений о грузе. Принятие может привести к проверке и окончанию кампании.</div>':''}<div class="grid-two"><div><div class="form-row"><div class="range-head"><label for="offer-price">Тариф за тыс. т</label><output id="price-output"></output></div><input id="offer-price" type="range" min="${(o.basePrice||o.price)*.65}" max="${(o.basePrice||o.price)*1.6}" step="0.01" value="${price}"></div><div class="form-row"><div class="range-head"><label for="offer-volume">Объём за квартал</label><output id="volume-output"></output></div><input id="offer-volume" type="range" min="${Math.max(20,Math.floor((o.baseVolume||o.volume)*.5))}" max="${Math.ceil((o.baseVolume||o.volume)*1.6)}" step="1" value="${volume}"></div><div class="form-row"><label for="offer-delay">Начало перевозок</label><select id="offer-delay"><option value="0">В этом квартале</option><option value="1">Через 1 квартал</option><option value="2">Через 2 квартала</option><option value="3">Через 3 квартала</option></select></div></div><div class="card" id="offer-preview"></div></div><div id="negotiation-response" class="info">Согласуйте условия с контрагентом. До уровня инженера 3 доступны два раунда переговоров; далее — три.</div>${why('Прогноз сначала обслуживает уже действующие обязательства. Оставшаяся мощность выделяется новому договору. Будущий старт даёт время подготовить сеть, но не гарантирует завершение всех работ.')}`,`<button class="secondary" data-action="reject-offer" data-id="${id}">Отказаться</button><button class="secondary" id="send-terms">Предложить условия</button><button class="primary teal" id="accept-terms">Заключить договор ${icon('check')}</button>`);
 const terms=()=>({price:Number($('#offer-price').value),volume:Number($('#offer-volume').value),startDelay:Number($('#offer-delay').value)});
 const preview=()=>{const t=terms();$('#price-output').textContent=money(t.price);$('#offer-price').setAttribute('aria-valuetext',money(t.price));$('#volume-output').textContent=`${num(t.volume)} тыс. т`;let f=E.offerForecast?.(state,id,t);if(!f){let clone=structuredClone(state);clone.contracts.push({...o,...t,start:state.quarter,end:state.quarter+o.duration,id:'preview'});const next=E.forecast(clone);f={delivered:next.delivered-currentForecast.delivered,revenue:next.revenue-currentForecast.revenue,expenses:next.expenses-currentForecast.expenses,net:next.net-currentForecast.net};}const a=f.offerAllocation;const delivery=a?.delivered??f.delivered;const revenue=f.incrementalRevenue??f.revenue;const profit=f.incrementalNet??f.net;const expenses=revenue-profit;$('#offer-preview').innerHTML=`<div class="eyebrow">Прогноз условий</div><div class="stats-row"><span>Выполнимый объём</span><b>${num(delivery,1)} тыс. т</b></div><div class="stats-row"><span>Выручка</span><b>${money(revenue)}</b></div><div class="stats-row"><span>Доп. расходы</span><b>${money(expenses)}</b></div><div class="stats-row"><span>Влияние на прибыль</span><b class="${profit>=0?'positive':'negative'}">${signed(profit)}</b></div><p>Нужны локомотивы и ${cargoNames[o.cargo].toLowerCase()==='уголь'?'полувагоны':o.cargo==='oil'?'цистерны':'крытые вагоны'} на ${num(t.volume)} тыс. т / кв.</p><p><b>Риск: ${delivery<t.volume*.85?'высокий':delivery<t.volume*.99?'умеренный':'низкий'}.</b> ${esc(a?.reason||f.note||'Учитываются ограничения маршрута и доступного парка.')}</p><p>Загрузка маршрута: ${num(Math.max(0,...(a?.paths||[]).flatMap(p=>p.lines.map(id=>f.edgeLoads[id]?.ratio||0)))*100)}%. ${esc(f.note||'')}</p>`;};
 $('.modal-content').addEventListener('input',preview);$('#send-terms').onclick=()=>{const r=E.negotiate(state,id,terms());beep();save();$('#negotiation-response').textContent=r.message+` Раунд ${r.offer?.rounds||o.rounds} из ${E.engineerLevel(state)>=3?3:2}.`;render();const updated=E.getOffers(state).find(x=>x.id===id);const counter=r.offer||updated;if(counter){$('#offer-price').value=counter.price;$('#offer-volume').value=counter.volume;}preview();};
 $('#accept-terms').onclick=()=>apply(E.acceptOffer(state,id,terms()),()=>contractsModal('active'));preview();
}
function financeModal(){const f=currentForecast, breakdown=f.breakdown||{};modal('Финансы без загадок','План следующего квартала',`<div class="grid-three"><div class="card"><div class="eyebrow">Бюджет</div><div class="big-number">${money(state.budget)}</div><span class="subtle">Баланс компании</span></div><div class="card"><div class="eyebrow">Прогноз результата</div><div class="big-number ${f.net>=0?'positive':'negative'}">${signed(f.net)}</div><span class="subtle">За квартал</span></div><div class="card"><div class="eyebrow">Кредит</div><div class="big-number">${money(state.debt)}</div><span class="subtle">Остаток долга</span></div></div><div class="grid-two spaced"><div><h3>Доходы и расходы</h3><div class="stats-row"><span>Выполненные перевозки</span><b class="positive">+${money(f.revenue)}</b></div><div class="stats-row"><span>Все расходы и штрафы</span><b>−${money(f.expenses)}</b></div>${Object.entries(breakdown).filter(([,v])=>typeof v==='number').map(([k,v])=>`<div class="stats-row"><span>${({variable:'Эксплуатационные расходы',operating:'Эксплуатация',network:'Содержание сети',fleet:'Содержание парка',penalties:'Штрафы за недопоставку',interest:'Проценты',debtPayment:'Кредитный платёж',maintenance:'Содержание',loanPayment:'Погашение кредита',revenue:'Выручка',operations:'Эксплуатация',networkMaintenance:'Содержание сети',fleetMaintenance:'Содержание парка'})[k]||esc(k)}</span><b>${money(v)}</b></div>`).join('')}${why('Выручка = фактически доставленный объём × согласованный тариф. Расходы включают эксплуатацию, содержание сети и парка, штрафы и кредит. Инвестиции списываются сразу при принятии решения. События могут изменить итог.')}</div><div><h3>Финансовая устойчивость</h3><p>Все суммы — балансируемые игровые параметры. Прогноз рассчитан по текущим договорам и состоянию сети.</p>${state.insolvencyQuarters>0?`<div class="warning">Бюджет отрицательный ${state.insolvencyQuarters} кв. Используйте восстановительный период: кредит, будущие перевозки или инвестиционные события.</div>`:''}<div class="inline-actions"><button class="secondary" data-action="loan">${icon('wallet')} Взять кредит</button><button class="secondary" data-action="repay" ${!state.debt?'disabled':''}>Погасить кредит</button></div><p class="subtle">Условия и доступный лимит проверяются перед выдачей. Кредит увеличивает расходы будущих кварталов.</p></div></div><h3>Результат по договорам</h3><div class="table-wrap"><table><thead><tr><th>Договор</th><th>Спрос</th><th>Перевезём</th><th>Выручка</th></tr></thead><tbody>${f.allocations.map(a=>`<tr><td>${esc(a.name)}${why(esc(a.reason||'Все ограничения маршрута соблюдены.'))}</td><td>${num(a.demand,1)} тыс. т</td><td>${num(a.delivered,1)} тыс. т</td><td>${money(a.revenue)}</td></tr>`).join('')}</tbody></table></div>`);}
function engineerModal(){const level=E.engineerLevel(state);const unlocks=['Ремонт, станции и обычные договоры','Дополнительные пути','Электрификация и переговоры','Проектирование новых линий','Крупные сетевые проекты'];modal('Профиль инженера','Опыт меняет возможности',`<div class="grid-three"><div class="card"><div class="eyebrow">Уровень</div><div class="big-number">${level}<small style="font-size:17px"> / 5</small></div></div><div class="card"><div class="eyebrow">Опыт</div><div class="big-number">${num(state.xp)}</div><span class="subtle">${LEVELS[level]?`до следующего: ${LEVELS[level].xp} опыта`:'Высший уровень'}</span></div><div class="card"><div class="eyebrow">Репутация</div><div class="big-number">${num(state.reputation)}<small style="font-size:17px"> / 100</small></div></div></div><h3>Путь развития</h3><div class="level-track">${unlocks.map((u,i)=>`<div class="${i+1===level?'current':''}"><b>${i+1<=level?'✓':icon('lock')} ${i+1}</b><small>${u}</small></div>`).join('')}</div><div class="info">Опыт начисляется за завершённые проекты, выполненные договоры и надёжную работу. Само расходование денег не даёт опыта.</div>${why('Репутация отражает надёжность перевозок и последствия решений. Критически низкая репутация ведёт к увольнению. Отказ от подозрительного офера безопасен.')}<h3>Достижения</h3>${state.achievements?.length?state.achievements.map(a=>`<div class="card" style="margin-bottom:8px">${icon('medal')} ${esc(typeof a==='string'?a:a.name||a.label)}</div>`).join(''):'<p>Первый завершённый проект станет началом вашей истории.</p>'}<div class="stats-row"><span>Перевезено за кампанию</span><b>${num(state.totalTransport,1)} тыс. т</b></div>`);}
function corridorModal(){const c=E.getCorridor(state);modal('Китай → Европа','Главный проект кампании',`<div class="card"><div class="card-top"><div><div class="eyebrow">Готовность коридора</div><div class="big-number">${num(c.percent)}%</div></div><div style="text-align:right"><b>${num(c.capacity,1)} / ${num(c.requiredVolume)} тыс. т</b><div class="subtle">сквозная мощность маршрута</div></div></div><div class="progress" style="margin-top:14px"><i style="width:${c.percent}%"></i></div></div><p>Постройте и модернизируйте конкретные объекты. После их завершения коридор должен пропускать ${num(c.requiredVolume)} тыс. т за квартал. Отдельный договор для победы не нужен. До готовности проект не приносит прямой выручки.</p><ol class="timeline">${c.stages.map((s,i)=>`<li class="${s.done?'done':''}"><span class="step-num">${s.done?'✓':i+1}</span><div><b>${esc(s.label)}</b><p>${s.done?'Объект готов':`Нужен инженер уровня ${s.requiredLevel}`} · ${names[s.type]}</p></div><button class="secondary" data-action="stage" data-id="${s.id}">${s.done?'На карте':'Открыть'} ${icon('arrow')}</button></li>`).join('')}</ol><div class="info">Новая линия Шу → Кызылорда — условный проект этой кампании. Зарубежные части пути показаны точками входа и выхода.</div>`);}
function selectStage(id){const s=E.getCorridor(state).stages.find(s=>s.id===id);if(!s)return;selected=s.type==='newLine'||(!station(s.target)&&!line(s.target))?{type:'station',id:s.a||'shu'}:{type:station(s.target)?'station':'line',id:s.target};world.focus(selected);render();if(!s.done)projectModal({type:s.type,target:s.target,a:s.a,b:s.b});else{closeModal();toast('Готовый объект выделен на карте');}}
function historyModal(){modal('История вашей сети','Квартальные отчёты',state.reports.length?state.reports.map((r,i)=>`<button class="list-link" data-action="report" data-index="${i}"><span><b>${quarterName(r.quarter)}</b><span class="subtle" style="display:block">Перевезено ${num(r.delivered,1)} тыс. т · ${esc(r.news?.[0]||'Квартал завершён')}</span></span><b class="${r.net>=0?'positive':'negative'}">${signed(r.net)}</b></button>`).join(''):'<div class="empty">Завершите первый квартал — здесь появится его отчёт.</div>');}
function reportModal(r){if(!r)return;if(r===state.reports[0]&&r.quarter>(state.uiLastReadReportQuarter??-1)){state.uiLastReadReportQuarter=r.quarter;save();render();}const news=(r.news||[]).slice(0,3);modal(`Квартал завершён`,quarterName(r.quarter),`<div class="grid-three"><div class="card"><div class="eyebrow">Изменение бюджета</div><div class="big-number ${(r.budgetDelta??r.net)>=0?'positive':'negative'}">${signed(r.budgetDelta??r.net)}</div><span class="subtle">С учётом вложений</span></div><div class="card"><div class="eyebrow">Доставлено</div><div class="big-number">${num(r.delivered,1)}</div><span class="subtle">тыс. т грузов</span></div><div class="card"><div class="eyebrow">Не выполнено</div><div class="big-number ${r.unserved>0?'negative':''}">${num(r.unserved,1)}</div><span class="subtle">тыс. т спроса</span></div></div><div class="report-news">${news.map((n,i)=>`<div class="card"><span>НОВОСТЬ 0${i+1}</span>${esc(typeof n==='string'?n.text||n:n.text||n.title)}</div>`).join('')}</div><div class="grid-two"><div><h3>Денежный результат</h3><div class="stats-row"><span>Выручка</span><b>${money(r.revenue)}</b></div><div class="stats-row"><span>Расходы</span><b>${money(r.expenses)}</b></div><div class="stats-row"><span>Инвестиции за квартал</span><b>−${money(r.investments)}</b></div><div class="stats-row"><span>Результат событий</span><b>${signed(r.eventMoney||0)}</b></div><div class="stats-row"><span>Движение по кредиту</span><b>${signed(Math.round(((r.budgetDelta??r.net)-r.net+(r.investments||0)-(r.eventMoney||0))*10)/10)}</b></div><div class="stats-row"><span>Бюджет после квартала</span><b>${money(r.budgetAfter??state.budget)}</b></div>${why(esc(r.explanation||'Доход начислен только за выполненные перевозки. Содержание, штрафы и выплаты учитываются отдельно. Итоговый бюджет также учитывает события квартала.'))}</div><div><h3>Развитие сети</h3><div class="stats-row"><span>Коридор Китай → Европа</span><b>${num(r.corridor?.percent??E.getCorridor(state).percent)}%</b></div><div class="stats-row"><span>Состояние парка</span><b>${num(r.fleetCondition??state.fleet.reduce((v,x)=>v+x.condition,0)/state.fleet.length)}%</b></div><div class="stats-row"><span>Завершено проектов</span><b>${r.finished?.length||r.completedProjects?.length||r.completed?.length||0}</b></div></div></div>${r.allocations?.length?`${(r.finished||[]).length?`<h3>Завершённые объекты</h3><p>${r.finished.map(p=>`${names[p.type]}: ${p.target?(station(p.target)?.name||line(p.target)&&routeName(line(p.target).a,line(p.target).b)||p.target):routeName(p.a,p.b)}`).map(esc).join('<br>')}</p>`:''}<h3>Почему изменились перевозки</h3>${r.allocations.map(a=>`<details class="why"><summary>${esc(a.name)} · ${num(a.delivered,1)} / ${num(a.demand,1)} тыс. т</summary><p>${esc(a.reason)}</p></details>`).join('')}`:''}`,`<button class="secondary" data-action="history">История отчётов</button><button class="primary teal" data-action="close-modal">Продолжить развитие ${icon('arrow')}</button>`);}
function settingsModal(){modal('Ваша кампания','Настройки и сохранение',`<div class="info">Кампания сохраняется автоматически в этом браузере после каждого решения и завершения квартала. Экспортируйте файл, чтобы сохранить отдельную копию.</div><div class="grid-two"><button class="secondary" data-action="save">${icon('save')} Сохранить сейчас</button><button class="secondary" data-action="export">Экспорт кампании</button><label class="secondary" style="cursor:pointer">Импорт кампании<input type="file" id="import-save" accept="application/json,.json" hidden></label><button class="secondary" data-action="sound">${icon(sound?'volume':'mute')} Звук: ${sound?'включён':'выключен'}</button></div><h3>Управление</h3><p>Выберите станцию или участок на карте. Колесо мыши меняет масштаб, перетаскивание перемещает карту. Экономика продвигается по кнопке «Ход». Фоновые поезда и погода оживляют карту во время планирования. Пятисекундную анимацию хода можно пропустить. Итоги придут письмом в центре карты. Escape закрывает окно.</p><div class="inline-actions"><button class="secondary" data-action="help">${icon('help')} Как играть</button><button class="secondary danger-btn" data-action="new-game">Начать новую кампанию</button></div><p class="footer-meta">География: GeoNames / Wikidata · схема направлений: ADB / CAREC<br>Все экономические величины — игровые. <a class="small-link" href="./SOURCES.md" target="_blank">Источники и допущения</a></p>`,'',true);$('#import-save').onchange=async e=>{const file=e.target.files[0];if(!file)return;const r=E.validateSave(await file.text());if(!r.ok){toast(r.message);return;}modal('Загрузить кампанию?','Импорт проверен',`<p>Файл: ${esc(file.name)}. ${quarterName(r.state.quarter)}, бюджет ${money(r.state.budget)}. Текущая кампания будет заменена.</p>`,`<button class="secondary" data-action="settings">Отмена</button><button class="primary teal" id="confirm-import">Загрузить</button>`,true);$('#confirm-import').onclick=()=>{state=r.state;selected=null;save();closeModal();render();toast('Кампания загружена');};};}
function helpModal(){modal('Добро пожаловать на магистраль','Железнодорожный магнат: Казахстан',`<div class="info"><b>Ваша цель:</b> построить работоспособное звено коридора Китай → Европа. Кампания не ограничена по времени.</div><ol class="timeline">${[['Найдите ограничение','В начале участок Караганда → Астана изношен. Нажмите на него, сравните ремонт и дополнительный путь.'],['Подготовьте сеть и парк','Ремонт и модернизация — разные действия. Локомотивы и подходящие вагоны нужны одновременно.'],['Договоритесь о перевозках','Меняйте цену и объём. Прогноз покажет, сколько сеть действительно перевезёт. Можно отложить начало.'],['Завершите квартал','Поезда выполнят рейсы, работы продвинутся, появятся доходы и отчёт. Во время планирования экономика ждёт ваших решений. Откройте конверт в центре карты, чтобы прочитать итоги.'],['Постройте коридор','За реальные результаты растёт опыт. Новые уровни открывают пути, электротягу и новые линии.']].map(([a,b],i)=>`<li><span class="step-num">${i+1}</span><div><b>${a}</b><p>${b}</p></div></li>`).join('')}</ol>`,`<button class="primary teal" data-action="close-modal">К управлению сетью ${icon('arrow')}</button>`,true);}
function endingModal(){world.renderNow();const won=state.status==='won';const title=won?'Путь на запад открыт':state.status==='bankrupt'?'Кампания завершена: банкротство':state.status==='arrested'?'Кампания завершена: арест':'Кампания завершена: увольнение';let screenshot='';try{screenshot=$('#world').toDataURL('image/png');}catch{}modal(title,won?'Китай → Казахстан → Европа':'Итоги управления',`${screenshot?`<img class="end-map" src="${screenshot}" alt="Созданная вами железнодорожная сеть">`:''}<div class="grid-three"><div class="card"><div class="eyebrow">Кварталов</div><div class="big-number">${state.quarter-state.startedQuarter}</div></div><div class="card"><div class="eyebrow">Перевезено</div><div class="big-number">${num(state.totalTransport)}</div><span class="subtle">тыс. т</span></div><div class="card"><div class="eyebrow">Репутация</div><div class="big-number">${num(state.reputation)}</div></div></div><p>${won?'Вы построили все объекты и обеспечили сквозную мощность маршрута. Казахстанское звено транзитного коридора готово. Можно продолжать развивать сеть.':state.status==='arrested'?'Проверка подтвердила серьёзное нарушение при перевозке подозрительного груза. Руководитель отстранён; кампания окончена.':state.status==='bankrupt'?'Период восстановления закончился с отрицательным бюджетом. Сеть перешла под внешнее управление.':'Репутация опустилась до критического уровня. Руководство компании назначило нового управляющего.'}</p><div class="info">Ваш стиль: ${state.reputation>=75?'надёжный стратег':state.projects.length>2?'инфраструктурный реформатор':'прагматичный управленец'}. Построено новых направлений: ${state.lines.filter(l=>l.playerBuilt).length}.</div>`,`<button class="secondary" data-action="export">Сохранить историю</button>${won?'<button class="primary teal" data-action="close-modal">Продолжить кампанию</button>':'<button class="primary teal" data-action="new-game">Новая кампания</button>'}`);}
function endTurn(){if(animating||isOver())return;closeModal();clearTimeout(mailTimer);mailOpening=false;hideTip();animating=true;beep('turn');world.animateQuarter(true);render();const node=document.createElement('div');node.id='turn-progress';node.className='turn-overlay';node.innerHTML='<span class="turn-time"><i></i><i></i><i></i></span><span>Три месяца в пути</span><button data-action="skip-animation">Пропустить →</button>';document.body.append(node);animationTimer=setTimeout(finishTurn,5000);}
function finishTurn(){if(!animating)return;clearTimeout(animationTimer);const previousStatus=state.status;const r=E.advanceQuarter(state);animating=false;world.animateQuarter(false);$('#turn-progress')?.remove();save();render();if(!r.ok){toast(r.message);return;}if(state.status!==previousStatus&&state.status!=='playing')endingModal();}
function bottleneck(){closeModal();const f=currentForecast;const edge=Object.entries(f.edgeLoads||{}).sort((a,b)=>b[1].ratio-a[1].ratio)[0];if(f.unserved>0&&edge){selected={type:'line',id:edge[0]};world.focus(selected);render();toast('Выделен самый загруженный участок. Проверьте также парк и ограничения договора.');}else corridorModal();}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const d=el.dataset;switch(d.action){
 case'close-modal':closeModal();break;
 case'engineer-card':engineerCard();break;
 case'network-card':networkCard();break;
 case'advisor-card':advisorCard();break;
 case'work-card':workCard(d.id);break;
 case'dismiss-inspector':selected=null;render();break;
 case'open-mail':openMail();break;
 case'project':projectModal({type:d.type,target:d.target});break;
 case'build':buildModal(d.tab);break;
 case'fleet':fleetModal();break;
 case'buy':{const def=FLEET_TYPES[d.type]||{};const copy=structuredClone(state);const bought=E.buyFleet(copy,d.type);const after=E.forecast(copy);modal(`Купить: ${fleetNames[d.type]}`,'Пополнение общего парка',`${fleetIllustration(d.type)}<div class="stats-row"><span>Стоимость</span><b>${money(def.cost)}</b></div><div class="stats-row"><span>Мощность при 100% состояния</span><b>${num(def.capacity)} тыс. т</b></div><div class="stats-row"><span>Содержание</span><b>${money(def.maintenance)} / кв.</b></div><div class="stats-row"><span>Изменение перевозок</span><b>${after.delivered-currentForecast.delivered>=0?'+':''}${num(after.delivered-currentForecast.delivered,1)} тыс. т / кв.</b></div><div class="stats-row"><span>Изменение прибыли</span><b>${signed(after.net-currentForecast.net)} / кв.</b></div>${!bought.ok?`<div class="warning">${esc(bought.message)}</div>`:after.delivered-currentForecast.delivered<1?'<div class="info">Сейчас покупка не увеличит перевозки: ограничение находится в другом месте или не хватает спроса.</div>':''}${why(d.type==='electric'?'Электровоз работает только на полностью электрифицированном маршруте. Нужны соответствующие грузу вагоны.':'Покупка повышает мощность общего парка. Эффект зависит от доступной инфраструктуры и наличия остальных типов техники.')}${state.budget-def.cost<currentForecast.expenses?`<div class="warning">Остаток ${money(state.budget-def.cost)}. Расходы следующего квартала до покупки — ${money(currentForecast.expenses)}.</div>`:''}`,`<button class="secondary" data-action="fleet">Назад</button><button class="primary teal" id="buy-confirm" ${!bought.ok?'disabled':''}>Купить</button>`,true);$('#buy-confirm').onclick=()=>apply(E.buyFleet(state,d.type),fleetModal);break;}
 case'repair-fleet':{const v=state.fleet.find(v=>v.id===d.id);modal('Ремонт техники',esc(v?.name||''),`<div class="stats-row"><span>Стоимость ремонта</span><b>${money(Math.round(v.cost*(100-v.condition)/100*BALANCE.fleetRepairRate+(v.age>=v.life?v.cost*BALANCE.fleetLifeExtensionRate:0)))}</b></div><p>Восстановление состояния до 100%. Капитальный ремонт техники, достигшей срока службы, также продлевает её ресурс.</p><div class="stats-row"><span>Состояние</span><b>${num(v?.condition)}% → 100%</b></div>`,`<button class="secondary" data-action="fleet">Назад</button><button class="primary teal" id="repair-confirm">Отремонтировать</button>`,true);$('#repair-confirm').onclick=()=>apply(E.repairFleet(state,d.id),fleetModal);break;}
 case'contracts':contractsModal(d.tab);break;
 case'negotiate':negotiationModal(d.id);break;
 case'reject-offer':apply(E.rejectOffer(state,d.id),()=>contractsModal());break;
 case'cancel-contract':{const c=state.contracts.find(c=>c.id===d.id);modal('Расторгнуть договор?',esc(c.name),`<p>Компенсация: ${money(c.volume*c.price*BALANCE.contractCancellationRate)}. Репутация уменьшится на 2 пункта. Договор прекратит перевозки в этом квартале.</p>`,`<button class="secondary" data-action="contracts" data-tab="active">Назад</button><button class="primary" id="cancel-confirm">Расторгнуть</button>`,true);$('#cancel-confirm').onclick=()=>apply(E.cancelContract(state,d.id),()=>contractsModal('active'));break;}
 case'finance':financeModal();break;
 case'loan':modal('Резерв для развития','Кредит',`<div class="stats-row"><span>Сумма кредита</span><b>${money(BALANCE.loanSize)}</b></div><div class="stats-row"><span>Ставка за квартал</span><b>${num(BALANCE.loanInterest*100,1)}%</b></div><div class="stats-row"><span>Дополнительные проценты / кв.</span><b>${money(BALANCE.loanSize*BALANCE.loanInterest)}</b></div><div class="stats-row"><span>Общий лимит долга</span><b>${money(BALANCE.maxDebt)}</b></div><p>Основной долг погашается вручную в разделе финансов. Проценты списываются каждый квартал до погашения.</p>`,`<button class="secondary" data-action="finance">Назад</button><button class="primary teal" id="loan-confirm">Получить кредит</button>`,true);$('#loan-confirm').onclick=()=>apply(E.takeLoan(state),financeModal);break;
 case'repay':apply(E.repayLoan(state),financeModal);break;
 case'engineer':engineerModal();break;
 case'corridor':corridorModal();break;
 case'stage':selectStage(d.id);break;
 case'history':historyModal();break;
 case'report':reportModal(state.reports[Number(d.index)]);break;
 case'settings':settingsModal();break;
 case'help':helpModal();break;
 case'sound':sound=!sound;try{localStorage.setItem('ktz-sound',sound?'1':'0');}catch{}beep();render();if(currentModal==='Ваша кампания')settingsModal();toast(sound?'Звук включён':'Звук выключен');break;
 case'save':apply(save());break;
 case'export':{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Казахстан-квартал-${state.quarter+1}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Кампания экспортирована');break;}
 case'new-game':modal('Начать новую историю?','Новая кампания',`<p>Текущее локальное сохранение будет заменено. Перед началом можно экспортировать кампанию в настройках.</p>`,`<button class="secondary" data-action="settings">Отмена</button><button class="primary" id="new-confirm">Начать заново</button>`,true);$('#new-confirm').onclick=()=>{state=E.createGame();selected=null;world.resetView();save();closeModal();render();toast('Новая кампания началась');};break;
 case'end-turn':endTurn();break;
 case'skip-animation':finishTurn();break;
 case'bottleneck':bottleneck();break;
 case'select-station':selected={type:'station',id:d.id};closeModal();world.focus(selected);render();break;
 case'select-line':selected={type:'line',id:d.id};closeModal();world.focus(selected);render();break;
 case'layer':layer=d.layer;render();break;
 case'zoom':world.zoom(Number(d.value));break;
 case'reset-map':world.resetView();break;
 }});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='Tab'&&currentModal){const els=[...document.querySelectorAll('.modal button:not(:disabled),.modal input,.modal select,.modal a[href],.modal summary')].filter(el=>el.offsetParent!==null);if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}});
document.addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop')||($('.mini-window')&&!e.target.closest('.mini-window')&&!e.target.closest('[data-action]')))closeModal();});
render();
if(load.ok&&load.state){toast('Кампания продолжена с последнего решения');if(isOver())endingModal();}else {if(!load.backupKey)save();if(load.backupKey)toast('Сохранение повреждено: резервная копия сохранена. Открыта новая кампания.');else if(load.message&&!/нет|не найден|отсутств/i.test(load.message))toast(load.message);else toast('Добро пожаловать! Советник поможет найти первое узкое место.');}
