// The HUD is kept separate from the simulation. All actions are dispatched by app.js.
export function renderHUD({state,f,c,level,selected,animating,sound,layer,icon,esc,num,money,signed,quarterName,seasonNames,seasonIcons,names,detailHTML,projectName}) {
 const tip=(title,body)=>`data-tip="${esc(body)}" aria-label="${esc(title)}"`;
 const orb=(action,ic,title,body,extra='',tone='')=>`<button class="orbit-button ${tone}" data-action="${action}" ${tip(title,body)} ${extra}>${icon(ic)}</button>`;
 const unread=state.reports[0] && state.reports[0].quarter>(state.uiLastReadReportQuarter??-1);
 return `<header class="game-hud">
 <button class="engineer-avatar orbit-button" data-action="engineer-card" ${tip('Инженер',`Ваш инженер · уровень ${level} · репутация ${num(state.reputation)} из 100`)}><img src="./assets/engineer-avatar.png" alt="Портрет инженера"><span class="avatar-level" aria-label="Уровень ${level}">${level}</span><span class="avatar-reputation" aria-label="Репутация ${num(state.reputation)}">${num(state.reputation)}</span></button>
 <div class="hud-capsule calendar-capsule">${icon(seasonIcons[state.quarter%4])}<div><span class="hud-kicker">${seasonNames[state.quarter%4]} · ${2026+Math.floor(state.quarter/4)}</span><b>${['I','II','III','IV'][state.quarter%4]} квартал</b><small>${animating?'Время ускорено':'Планирование'}</small></div></div>
 <button class="hud-capsule money-capsule" data-action="finance"><span class="hud-money-icon">${icon('wallet')}</span><span><span class="hud-kicker">Бюджет</span><b>${money(state.budget)}</b></span></button>
 <button class="hud-capsule forecast-capsule" data-action="finance"><span><span class="hud-kicker">Прогноз за квартал</span><b class="${f.net>=0?'positive':'negative'}">${signed(f.net)}</b></span>${icon('chart')}</button>
 <div class="hud-utilities">${orb('sound',sound?'volume':'mute',sound?'Выключить звук':'Включить звук','Звуки интерфейса и завершения хода','','small-orbit')}${orb('settings','settings','Настройки и сохранение','Сохранить, загрузить или начать новую кампанию','','small-orbit')}</div></header>
 <nav class="command-rail" aria-label="Управление сетью">${orb('network-card','chart','Обзор сети',`Прогноз: ${num(f.delivered,1)} тыс. т · не выполнено ${num(f.unserved,1)} тыс. т`,'','network-orbit')}${orb('advisor-card','advisor','Советник',f.unserved>1?'Есть ограничения перевозок. Посмотрите советы инженеру.':'Рекомендации по развитию сети и коридора','','advisor-orbit')}
 ${state.projects.length?`<div class="rail-separator"></div><div class="work-orbits" aria-label="Работы в процессе">${state.projects.map(p=>{const progress=Math.max(0,Math.min(100,(p.duration-p.remaining)/p.duration*100));const ic=['upgrade','stationRepair'].includes(p.type)?'station':p.type==='electrify'?'bolt':'rails';return `<button class="orbit-button work-orbit" data-action="work-card" data-id="${esc(p.id)}" style="--progress:${progress}%" ${tip(`${names[p.type]}: ${projectName(p)}`,`${projectName(p)} · готово ${num(progress)}% · осталось ${p.remaining} кв.`)}>${icon(ic)}<span class="quarter-badge">${p.remaining}</span></button>`;}).join('')}</div>`:''}</nav>
 <section class="corridor"><div class="corridor-title"><strong>${icon('flag')} Китай <span style="display:inline;color:#8da39a">→</span> Европа</strong><button class="text-btn" data-action="corridor" aria-label="Этапы главного коридора"><b>${num(c.percent)}%</b>${icon('chevron')}</button></div><div class="stages">${c.stages.map((s,i)=>`<button class="stage ${s.done?'done':state.projects.some(p=>p.type===s.type&&(s.type==='newLine'?p.a===s.a&&p.b===s.b:p.target===s.target))?'active':''}" data-action="stage" data-id="${s.id}" title="${esc(s.label)}" aria-label="Этап ${i+1}: ${esc(s.label)}"></button>`).join('')}</div></section>
 ${selected?`<aside class="right-panel panel"><button class="inspector-close icon-btn" data-action="dismiss-inspector" aria-label="Свернуть сведения">${icon('close')}</button>${detailHTML()}</aside>`:''}
 <div class="map-caption"><h1>Казахстан</h1><p>Железная дорога начинается с вашего решения</p></div>
 <div class="map-tools">${orb('layer',layer==='network'?'layers':'map',layer==='network'?'Показать загрузку':'Показать сеть','Переключить схему сети и загрузку участков',`data-layer="${layer==='network'?'load':'network'}"`,'small-orbit')}${orb('zoom','minus','Отдалить','Уменьшить масштаб карты','data-value="-1"','small-orbit')}${orb('reset-map','target','Показать всю страну','Вернуться к общему виду Казахстана','','small-orbit')}${orb('zoom','plus','Приблизить','Приблизить карту и рассмотреть станции','data-value="1"','small-orbit')}</div>
 <nav class="game-dock" aria-label="Главные разделы">${[['build','build','Строительство','Проекты, ремонт и новые направления'],['contracts','contract','Договоры','Предложения, переговоры и действующие перевозки'],['fleet','train','Подвижной состав','Покупка и ремонт общего парка'],['finance','chart','Финансы','Полный расчёт доходов, расходов и кредита'],['engineer','medal','Навыки инженера','Уровни, открытые возможности и достижения'],['history','history','История','Квартальные отчёты вашей кампании']].map(([a,i,t,d])=>orb(a,i,t,d,'',`dock-${a}`)).join('')}</nav>
 <button class="turn-button" data-action="end-turn" aria-label="Ход" data-tip="Завершить квартал и отправить поезда в путь" ${animating||['bankrupt','dismissed','arrested'].includes(state.status)?'disabled':''}><span class="turn-symbol">${icon(animating?'clock':'sun')}</span><span><b>${animating?'В пути':'Ход'}</b><small>Один квартал</small></span>${icon('arrow')}</button>
 ${unread&&!animating?`<div class="quarter-mail"><button class="mail-orbit orbit-button" data-action="open-mail" aria-label="Открыть отчёт за прошедший квартал" data-tip="${esc(quarterName(state.reports[0].quarter))}. Откройте письмо с итогами."><span class="envelope"><span class="envelope-letter"></span><span class="envelope-front"></span><span class="envelope-flap"></span><i></i></span><span class="mail-seal">1</span></button><span class="mail-label">Вам письмо<small>Итоги квартала</small></span></div>`:''}`;
}
